sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install:
  - composer install --no-scripts --no-interaction --prefer-source
script:
  - php vendor/bin/phpspec run
matrix:
  allow_failures:
    - php: 7.0
